title: Homepage
timezone: UTC
collections:
  authors:
    output: true
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
  - jekyll-feed
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: assets/img
    values:
      image: true
jekyll_admin:
  hidden_links: null
