title: Maple60のホームページ
timezone: JST
collections:
  authors:
    output: true
description: >-
  Rを含むプログラミングなどのメモを書いていきます。
baseurl: ''
url: ''
# theme: minima
plugins:
  - jekyll-feed
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: assets/img
    values:
      image: true

collections:
  - data