version: '3'
services:
  app:
    image: jekyll/jekyll
    command: bundle update && bundle exec jekyll serve --force_polling
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    tty: true
    stdin_open: true
